`$sh IS_LOCAL="${IS_LOCAL:-true}" ./_util.sh header "table-driven-lexing.adoc" '
date = 2025-06-29
tags = ["compilers"]
' $`

I always heard that table-driven parsing was optimal, and in theory I knew it was possible, but I never really understood how.
Well, past self, here is how it is done.

== Introduction to Compilation

If your input is the highest level-representation, 'compiling' in computer science is the process of taking some input and progressively lowering{wj}footnote:[The term 'lowering' probably arose from how High-Level Languages evolved out of Lower-Level Languages and required a more formalised process of parsing.] it into other representations.
For example, the Rust compiler transforms:

|===
| Rust{wj}footnote:[https://rustc-dev-guide.rust-lang.org/part-3-intro.html[Rust Compiler Development Guide: Source Code Representation]] | Zig{wj}footnote:[Lugg, Matthew. link:https://youtu.be/KOZcJwGdQok?t=822[Data-Orientated Design Revisited: Type Safety in the Zig Compiler - Matthew Lugg]. 13:42. Software You Can Love, Milan 2024. Archived at YouTube, Zig SHOWTIME on 2024-09-05.]{wj}footnote:[Hashimoto, Mitchell. https://mitchellh.com/zig[Zig]. Mitchell Hashimoto, 2025.]

| source code (arbitrary text) | source code
| tokens via the __lexer__     | tokens by the __tokenizer__
| AST via the __parser__        | AST via the __parser__
| High-level Intermediate Representation (HIR) | Zig IR by __AstGen__
| Typed HIR                                    | Analyzied IR by __Sema__
| Mid-level A IR                               | Machine IR by __CodeGen__
| https://en.wikipedia.org/wiki/LLVM[LLVM] IR  | LLVM IR (when the LLVM backend is used)
| Machine code.                                | Machine Code
|===

Each step is essentially an Array/Tree of structs, and compilation is iteratively taking one representation and transform it into the next until you have your output.
More specifically, each step in this process is categorizing your input with types (structs), but the structs you use are often ambiguous until further down the pipeline, so each step is just categorizing it better and better.
And at each step, different operations become more feasible, e.g. type inference, optimizations, etc.

== Approaches to Lexing

The specific names for the lower processes, like lexing or parsing, may be called different things or may not even be a step in every compiler.
But, __lexing__ in compilers does typically always refer to grouping source-code characters together into more a useful token struct.
__Parsing__ often refers to the taking those tokens and transforming them into an AST, but sometimes it refers to __lexing__ and transforming into an AST combined.
There is no particular reason to split/combine steps, or have less or more steps, if you were to program your own compiler, do what you find helps.
There's nothing special about these steps, but from experience, splitting lexing and parsing from other steps is a "good split point" on problem.{wj}footnote:[Blow, Jonathan and Muratori, Casey. https://youtu.be/MnctEW1oL-E?t=1091[Discussion: Making Programming Language Parsers, etc (Q&A is in separate video)]. 18:11-20:00. YouTube, Jonathan Blow, 2020-03-30.]


=== link:https://en.wikipedia.org/wiki/Lex_(software)[Lex]/link:https://en.wikipedia.org/wiki/Flex_(lexical_analyser_generator)[Flex]/link:https://en.wikipedia.org/wiki/Yacc[Yacc]/link:https://pest.rs/[Pest]/etc.

After writing a document for your project in a custom domain-specific language (DSL), these programs will do the lexing for you.{wj}footnote:[
Yacc and Pest are do more than just lexing.
Yacc uses the infamous Backus-Naur Form of languages that you often on many languages.
For example, link:https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_10_02[POSIX sh (search 'Shell Grammar Rules')] and link:https://ziglang.org/documentation/master/#Grammar[Zig (search 'Grammar')].
]
However, using these tools often is more pain than it is worth, especially for the older tools.
See https://www.nothings.org/computer/lexing.html[this article] by Sean Barrett on arguing against lex/fles.

Moreover, writing a lexer only takes a few hours, roughly how long it will take to understand how to integrate an external tool/library into your build.{wj}footnote:[
The parser into non-typed AST usually takes me a few days, but this is usually because this where I am also makign decisions on langauge design.
]
Is it really worth adding a dependency just to save a few hours?
And even if you deem it so, is it really worth learning a new DSL just, that you probably will not touch again and forget, just to save those few hours?

=== Handmade Switch-Based Lexing

A lexer (and indeed the parser) essentially are just a finite state machine.
You have some enum for you state, you loop over the input text, you switch on the state, then you switch on the text, and then update the state and maybe output.

Generally, the advantage of handmade lexers is that you can tailor your error messages much better.
Compiler error messages are the UI of your compiler, so it is fairly import to get them right.
There's a reason why Rust values error messages and was inspired by Elm's error messages.{wj}footnote:[
"Those of you familiar with the Elm style may recognize that the updated --explain messages draw heavy inspiration from the Elm approach." Turner, Sophia June. https://blog.rust-lang.org/2016/08/10/Shape-of-errors-to-come/[Shape of errors to come]. Rust-Lang, 2016-08-10.
]

Here is an example written in Zig.

[source,zig]
----
const LexemeType = enum  {
  Whitespace,
  Identifier,
  Comment,
  LParen,
  RParen,
  Number,
};
struct Lexeme {
    type: LexemeType,
    start: u32, // Mapping to original text
    close: u32, // Mapping to original text
}

// []u8 is the string representation in zig
fn lexer(input: []u8, output: std.ArrayList(Lexeme)) {
    const States = enum {
        whitespace,
        ident,
        function,
        number,
    };
    var std.ArrayList
    var state: States = .whitespace;
    var cursor = 0;
    for (0.., input) |i, ch| {
        switch (state) {
            .whitespace => switch (ch) {
                'a'..'z' => {
                  state = .ident,
                  cursor = i;
                }
                _ => {},
            },
            .ident => switch (ch) {
                ' ' => {
                    state = .whitespace,
                    output.append(Lexeme {
                        .type = .Identifier,
                        .start = cursor,
                        .close = i;
                    });
                    cursor = i;
                }
                _ => {},
            },
        }
    }
}
----



=== Table-Driven Lexing

[NOTE]
Lexing (are there exceptions?) can be solved as a Deterministic Finite Automata (DFA), which means they can always be solved by state transition table (by definition of a DFA).
So you can always write a lexer as table-driven, but the question was always how exactly.

See https://github.com/yueleshia/eyg/blob/main/src/s1_lexer.zig

Explanation coming soon...

== Closing Thoughts

In JAI, of the entire compilation process, lexing and parsing is roughly less than 5% of the total compiler time.{wj}footnote:[Blow, Jonathan. link:https://youtu.be/MnctEW1oL-E?t=1362[Discussion: Making Programming Language Parsers, etc. (Q&A is in a separate video]. 22:42-23:02. YouTube, Jonathan Blow, 2020-03-30.]
Although, The speed of a compiler does I imagine lexing is probably at most 1% of compilation time.
So one might argue that optimizing this part of a compiler is not that fruitful.

But surprsingly, from writing my own table-driven lexer, I actually found that it was a lot easier to iterate on the table-driven implementation.
Because the implementation is so simple, assuming your programming language has a pleasant way to compile-time generate tables, it is extremely to easy to read and make modifications.
The only difficult part of the implementation was sovling how to branchlessly output different sized tokens (e.g. "const" vs "for") or errors.
But, I no longer have to modify that part of the code, even when evolving my target programming language.
And this was good practice for branchless programming.

Now that I have been through it once, I think I will always program lexer as table-driven.
Some error messages that I would have emitted in the lexer were moved to the parser, because of the lack of leeway in the table-driven implementation, but for the most part, other than that, it has not been limiting.
Rather, it's been more plesant to design with, so surprisingly, there have been no down sides, unlike most optimizations.
Assuming you have a good compile-/build-time table generation programming language.

== See also

* I have already reference this article, but many thanks to https://www.nothings.org/computer/lexing.html[this article] by Sean Barrett (RAD Game Tools game programmer), nothings, 2015-05-01.
Barrett walks the reader through to table-driven lexing via a set of optimization decisions.
Table-driven parsing finally clicked for me after reading this.

* And https://www.youtube.com/watch?v=rq1DRuB9p7w[here] is a discussion between Barett and Jonathan Blow (Thekla game designer/programmer) on Barrett's C Compiler.

* Also see the weekly compiler discussions hosted by link:https://www.youtube.com/@compilers[Cliff Click] (author of Sea of Nodes).
