`$sh IS_LOCAL="${IS_LOCAL:-true}" ./_util.sh header "tf-enterprise.adoc" '
date = 2025-06-29
tags = ["OpenTofu", "Terragrunt"]
' $`

This all should be equally valid for both Terraform and OpenTofu (TF).

== Managing Authentication

As TF is an orchestrator for executables, authentication is entirely dependant on the provider.
Typically, you can always login to a platform via its CLI's OAuth flow.{wj}footnote:[You would think that using the CLI tool should be equivalent to TF since they both are design for calling a platform's REST API, but sadly this is not always the case. For example, the Atlas MongoDB CLI can login with oauth via `atlas auth login`, but the terraform provider cannot use this and requires either an API or service account credentials.]
However, complication arises when your single tenant{wj}footnote:[A tenant is a single login, but at the organizational level. This is so that a single organizational can have different accounts, for example one account for development and one account for production] needs access to different accounts for different release phases, e.g. development, QA, E2E, staging, and production.

Single Sign-On (SSO) flows typically resolve authentication, but TF requires a `tofu init -reconfigure` for each account as the tfstate is stored on said account.

On AWS the full command looks something like:

[source,shell]
----
tofu init \
  --backend-config bucket='s3'
  --backend-config locks=
  --var-file development.tfvars
----

Unfortunately, vanilla terraform cannot automate backend configuration (i.e. you can use variables), but as of OpenTofu 1.8.0{wj}footnote:[cam72cam, ollevche. https://github.com/opentofu/opentofu/pull/1718[PR 1718: Static Evaluation Base, Module Sources, Backend Config]. GitHub, 2024-06-24-06.] you can use variables in backend configuration.
Some solutions are:

|===
| Header | Pros | Cons

| straight `terraform init -reconfigure ...` | Easy | This is the kind of manual work that never becomes muscle memory.
| TF workspaces | Once you have init each workspace, you never have to init again
a|
* Terraform gives no visual indicator of what workspace you are on, so you are likely to apply on the wrong account.
* Not a compelling enough feature, so most team members are unlikely to buy into using this. But there's nothing wrong with just using it on your own computer.

| Shellscript  | Easy and familiar to DevOps engineers | Windows/Linux/Mac script portability can be an issue.
| Terragrunt/Terranix/etc. wrappers | As it is a drop in-replacement, this is relatively easy sell. Additionally you get some nice automation options | Yet another tool on the very large DevOps tech stack, but most do not need to ever interact with Terragrunt scripting once it is setup.
|===

== Directory Structure

At small a number of resources (100s of resources with < 15 minute to apply), you can generally do whatever you want.
At large a number of resources, you began to separating your tfstate into apply's that can be run in parallel.
CI/CD on GitHub has a 1 hour timeout, and it is miserable to be iterating when it takes longer than 15 minutes to just plan your changes.

=== Modules (Single Directory)
For an individual module, Hashicorp https://developer.hashicorp.com/terraform/language/modules/develop/structure[recommends] having `main.tf`, `variables.tf`, and `outputs.tf`.
This practice provides a single centralised place to look for inputs and outputs for those looking to use your module.
I would recommend mostly organizing files around compute.
Architecture decisions are based around if thinking in units of compute, so this makes it easy to track the permissions a given component has.
Additionally, when adding a new component, it is easy to copy paste.

So rather than

----
.
├── variables.tf
├── outputs.tf
├── api_gateway.tf
├── load_balancer.tf
└── containers.tf
----

I would recommend something more like this.

----
.
├── variables.tf
├── outputs.tf
├── networking.tf       # Combining load_balancer and api_gateway
├── security_groups.tf  # i.e. AWS Firewall settings
├── container_backend.tf
├── container_frontend.tf
└── container_email.tf
----

=== Project (Group of Directories)

Different projects of course will have different requirements, so I would not say that there is a one-size-fits-all solution.
In small projects, it is easiest to just put everything in one folder, but as you scale, you will want to break your project up.
Decomposing your project is asking the question what parts of your project can separated into mostly standalone submodules.
Aside from conceptual concerns, you will also want to answer the following:

* What is the relative lifecycle of a candidate module? If a candidate needs to be updated separately from other modules, then you will need a separate folder.
* How long does it take to apply? You probably want TF apply's to be under an hour.

Assign a folder to each submodule: these correspond to separate TFStates.
Within a single folder, you put everything except resources that require touch other submodules.
Cross-cutting resources will have be separated into their own folder as they require both submodules to be provisioned before they themselves can be provisioned.

For example, if you are an event driven-architecture with SNS->SQS, I would create an SNS in writer module, the SQS in the reader module, and then subscriptions and permissions in the dependencies.

----
.
├── networking/
├── emailing-module/
|   └── emailing-dependencies/
└── backend-frontend-module/
    └── backend-frontend-dependencies/
----

If your project is big enough that you wish to separate out dependencies as in the example above, and you are wondering which folder to put the resources, my golden rule is always follow the compute.
If the SNS->SQS subscription is being read by the emailing module, then put it together with the emailing module.

=== Project Pattern: Thin Module Importing Thick Source

----
.
├── source/
├── development/
├── qa
├── integration/
├── staging/
└── production/
----

Each module should be extremely minimal, only using `source/` as a module.
If there are items specific to a phase, you pass in the phase name, and do a `count = var.phase != "production" ? 0 : 1` or `for_each = { for ... if var.phase == "p" }`.

For example, your development/ folder will only have the file:

[source,hcl]
----
# development/main.tf
module "phase" {
  source = "../source"

  phase = "development"
}
----
