`$sh IS_LOCAL="${IS_LOCAL:-true}" ./_util.sh header "tf-secrets.adoc" '
date = 2025-06-28
tags = ["OpenTofu"]
' $`

Ah, secrets.

In context of TF, the primary concern is ensuring only the right people/things can view them, and no one else.
For small teams, you essentially just want to avoid checking in your git.
However, TF introduces an additional attack vector you might not be aware of: the TF stores all passwords (used or read) in plaintext within the tfstate.
OpenTofu 1.11 (https://github.com/opentofu/opentofu/issues/2834[planned]) and Terraform 1.10 introduce the new `ephemeral` syntax that partially mitigates this problem.

== The Problem Space


For larger teams, secrets are secured by assigning its management subtasks to different people so that no one person has full access.

. Creation of the secret value (e.g. creating an API key at a service provider, generating a public-private key pair)
. Provisioning the secret store (e.g. creating an entry in AWS secretsmanager)
. Setting the secrets' permissions
. Maintaining and putting values into secret stores
. Verifying the value is correct (when using asymmetric keys)
. Using the value (e.g. Configuring cognito login on a load balancer or the application authenticating a service)
. Rotating the secret

For the most sensitive secrets, each subtask is the responsibility of a separate person.
When working for payments in role responsible for IaC, I was in charge of all seven tasks, but for the most sensitive tasks, I was in charge of just (2) provisioning and (3) permissions.
All tasks can be accomplished with TF, but the tfstate foot gun crops up with step (4) putting the value and (6) using the value.

== Using Secret with HCL

One way to implement authenticating and authorization is by placing it on the infrastructure level, a type of negative space architecture.
You architect your application so the public can only interact with your application through one entry point and require authentication a that point.

Take a load balancer with a OAuth configured on it for example.
An incoming request hit load balancer, is redirected to check the login details receiving a token, is redirected back to the load balancer that checks the token, and then is forwarded to your application.

Your TF must to configure a client ID and secret on the load balancer, probably reading from secretsmanager.
You will have to set up a separate system to track values and put values into secret (since by its nature of infrastructure as __code__, we do not want to hard code it), but but ideally we want everything else (configuring the load balancer) to be automated.

But if it appears as either used in data, a resource, or output, TF will record the values as plaintext in the tfstate. Here is an example:

[source,hcl]
-----
# main.tf
data "aws_secrets_manager_version" "example" {
  secret_id = ""
}

# terraform.tfstate
{
...
}
-----

This partially defeats the purpose of having setting a whole second process around maintaining secret values and putting values into secrets.
Here are some solutions:

=== Encrypt TFState

The easiest option is to just use secrets normally and security your tfstate is encrypted with.
Limit the permissions to the tfstate bucket, and you have a working solution.
Here is an example of configuring cognito:

[source]
----
resource "aws_secretsmanager_secret" "example" {
  name        = "/secret/name"
  description = "This is an example secret"
}

resource "aws_secretsmanager_secret_version" "example" {
  secret_id     = aws_secretsmanager_secret.example.id
  secret_string = "<<<to-be-overriden>>>" # The initial dummy value
}

data "aws_secretsmanager_secret_version" "latest" {
  # This is necessary as otherwise data will be schedule in parallel with provisioning
  # and will then fail because the secret does not exist yet
  depends_on = [aws_secretsmanager_secret.example]

  secret_id = data.aws_secretsmanager_secret.example.id
}

resource "aws_lb_listener" "front_end" {
  load_balancer_arn = "<<<some_arn>>>"
  port              = "80"
  protocol          = "HTTP"

  default_action {
    type = "authenticate-cognito"

    authenticate_cognito {
      user_pool_arn       = "arn:aws:cognito:us-east-1:1234567890:userpool/us-east-1_0xkj340"
      user_pool_client_id = "1234567890abcdef"
      user_pool_domain    = "abcdefghijklmnopqrstuvwxyz1234567890"
    }
  }

  default_action {
    type             = "forward"
    target_group_arn = "<<<some_other_arn>>>"
  }
}
----

[NOTE]
The lifecycle feature, `lifecycle { ignore_changes [...] }`, may come in handy.


==== Using local-exec

Local-exec workflows are not a first-class workflow{wj}footnote:[https://opentofu.org/docs/language/resources/provisioners/syntax/["Provisioners are a last resort"]] as they do not follow the regular CRUD lifecycle.

[source,hcl]
----
resource "aws_secretsmanager_secret" "example" {
  name        = "/secret/name"
  description = "This is an example secret"
}

resource "aws_secretsmanager_secret_version" "example" {
  secret_id     = aws_secretsmanager_secret.example.id
  secret_string = {
    client_id = "" # To be overwridden by something outside of TF
    client_sc = "" # To be overwridden by something outside of TF
  }
}

data "aws_secretsmanager_secret_versions" "example_changes" {
  secret_id = aws_secretsmanager_secret.example.id
}

resource "terraform_data" "use_secret_value_secretly" {
  # A change in version id will cause this to be reprovisioned, retriggering the local-exec
  triggers_replace = [
    for scr in data.aws_secretsmanager_secret_versions.example_changes.versions :
    scr.version_id
    if scr.version_stage == "AWS_CURRENT"
  ]

  provisioner "local-exec" {
    command = ["sh", "-c", <<-EOT
      x="$( aws secretsmanager get-secret-value --secret-id "${aws_secretsmanager_secret.example.id}" )" || exit "$?"
      value="$( printf %s\\n "$x" | jq ".SecretString | fromjson" )" || exit "$"

      client_id="$( printf %s\\n "${value}" | jq '.client_id' )"
      client_sc="$( printf %s\\n "${value}" | jq '.client_sc' )"

      pool_arn="arn:aws:cognito:us-east-1:1234567890:userpool/us-east-1_0xkj340"
      target_group_arn="arn:aws:elasticloadbalancing:us-east-1:1234567890:targetgroup/tg-example/aq1sw2de3"
      listener_arn="arn:aws:elasticloadbalancing:us-east-1:1234567890:listener:lb-example/qwer1234"

      aws elbv2 modify-listener \
        --listener-arn    "$listener_arn" \
        --default-actions "Type=authenticate-cognito,AuthenticateCognitoConfig={UserPoolArn=$pool_arn,UserPoolClientId=$client_id,UserPoolDomain=$client_sc},Type=forward,TargetGroupArn=$target_group_arn" \
      # end
    EOT
    ]
  }
}
----

== Maintaining and Putting Secret Values

At the end of the day, someone is responsible for doing knowing the secret values, putting them into the secret storage, and updating them when they change.
More often than not, the master file for all these managed secret values is an excel file.
And if the manager is a team of one, then the file lives on their pc locally, if team of many, then it lives on a google drive.
Having all the secrets, especially of your not top-priority secrets, is definitely extremely convenient.
But surely we can do better.

=== Automation

TF is not really the solution for secret value maintenance.
There are other solutions like: sacrificing a centralized text file and using the cloud secret manager directly, Bitwarden, HashiCorp Vault, etc.

However, here is one centralized text solution.
You use a single entry in the secret store to store all secret values.
The workflow is as follows:

. (Out of band) Edit your master secret file locally as you wish.
. Your TF reads the secret value. It uses a local-only tfstate.
. If it is a newer version than the master file on your local, update it, otherwise update the secret store.
. Put secret values


=== Example

In the following example, we use a local file that contains an incrementing number to keep track of the versions.
This can be run locally.
For an AWS implementation, I have left the comments.

*secrets.json*
[source,json]
----
{
  "/email/secret": { "client_id": "12345", "client_scr": "password" }
}
----

*main.tf*

[source,hcl]
----
locals {
  local_path   = "secrets.json"
  remote_path  = "./secrets_remote.json"
  #remote_path  = "/production/master-secret-file"
  version_path = "version.txt"
}

data "external" "latest_secret" {
  program = ["sh", "-c", <<-EOT
    remote_path="${local.remote_path}"
    local_path="${local.local_path}"
    local_version_path="${local.version_path}"

    # Or: remote_secret="$( aws secretsmanager get-secret-value \
    #       --secret-id "$remote_path" \
    #       --query SecretString \
    #       --format text
    #     )" || exit "$?"
    remote_secret="$( cat "$remote_path" )" || remote_secret=""
    [ -z "$remote_secret" ] && remote_secret="{}"
    local_value="$( cat "$local_path" )" || local_value=""
    [ -z "$local_value" ] && local_value="{}"

    local_version="$( cat "$local_version_path" )"
    [ -z "$local_version" ] && local_version=0
    if ! printf %s\\n "$local_version" | grep "^[0-9]*$" >/dev/null; then
      printf %s\\n "Please put only numbers in $local_version_path" >&2
      exit 1
    fi

    remote_version="$( printf %s\\n "$remote_secret" | jq --raw-output '.version // "0"' )" || exit "$?"
    remote_value="$( printf %s\\n "$remote_secret" | jq '.value // {}' )" || exit "$?"

    printf %s\\n "Compare: local $local_version < remote $remote_version" >&2
    if [ "$local_version" -lt "$remote_version" ]; then
      printf %s\\n "Using remote" >&2
      printf %s\\n "$remote_secret" | jq --raw-output '.secret // {}' >"$local_path"

      version="$remote_version"
      output="$remote_value"
    elif [ "$local_value" = "$remote_value" ]; then
      printf %s\\n "No changes" >&2
      version="$local_version"
      output="$local_value"
    else
      printf %s\\n "There are updates for the remote" >&2

      version="$(( remote_version + 1 ))"
      output="$local_value"
    fi

    printf %s\\n "$output" | jq --arg version "$version" '{
      version: $version,
      value:   tojson,
    }'
  EOT
  ]
}

resource "local_file" "version" {
  filename = "version.txt"
  content  = data.external.latest_secret.result.version
}

resource "aws_secretsmanager_secret_version" "remote_secret" {
  secret_id     = local.remote_path
  secret_string = jsonencode({
    version = data.external.latest_secret.result.version
    value   = jsondecode(data.external.latest_secret.result.value)
  })
}

resource "local_file" "secret_remote" {
  filename = local.remote_path
  content  = jsonencode({
    version = data.external.latest_secret.result.version
    value   = jsondecode(data.external.latest_secret.result.value)
  })
}

resource "local_file" "put" {
  for_each = jsondecode(data.external.latest_secret.result.value)

  filename = each.key
  content  = each.value
}
## replace with the following for AWS
#resource "aws_secretsmanager_secret_version" "put" {
#  for_each = jsondecode(data.external.latest_secret.result.value)
#
#  secret_id     = each.key
#  secret_string = each.value
#}

output "value" {
  value = data.external.latest_secret.result
}

resource "aws_secretsmanager_secret_version" "put" {
  for_each = jsondecode(data.external.latest_secret.result.value)

  secret_id     = each.key
  secret_string = each.value
}
----

With ephemeral resources, maybe this workflow can be improved.
We are looking to replace the data.external.latest_secret with an ephemeral resource.
